name: Linux-armhf

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.config.name }} Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config: 
          - os: ubuntu-latest
            name: Linux armhf
            other_linker_flags: ''
            arch: armhf
            output: libRemoteInput-armhf.so
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        
    - name: Update Sources - Linux armhf
      if: matrix.config.arch == 'armhf'
      run: |
        sudo sed -Ei 's/^deb /deb \[arch=amd64\,i386\] /' /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ bionic main restricted" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ bionic-updates main restricted" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ bionic universe" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ bionic-updates universe" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ bionic multiverse" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ bionic-updates multiverse" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ bionic-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
        
        sudo dpkg --add-architecture armhf
        sudo apt-get update
        
    - name: Dependencies - Linux armhf
      if: matrix.config.arch == 'armhf'
      run: |
        sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
        sudo apt-get install libprocps-dev:armhf mesa-common-dev:armhf libglu1-mesa:armhf libglu1-mesa-dev:armhf libgl1-mesa-glx:armhf libgl1-mesa-dev:armhf libglfw3-dev:armhf cmake

    - name: CMake Generate Build Files
      if: matrix.config.arch == 'armhf'
      run: |
        cmake -S '${{ github.workspace }}' -B '${{ github.workspace }}/cmake-build-release' -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=armhf -DCMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=/usr/bin/arm-linux-gnueabihf-g++ -DCMAKE_BUILD_TYPE=Release -DOTHER_LINKER_FLAGS:STRING=${{ matrix.config.other_linker_flags }} -G "CodeBlocks - Unix Makefiles"

    - name: Build
      if: matrix.config.arch == 'armhf'
      run: |
        cmake --build '${{ github.workspace }}/cmake-build-release' --target all -- -j 4