name: Linux-armhf

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.config.name }} Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config: 
          - os: ubuntu-latest
            name: Linux armhf
            other_linker_flags: ''
            arch: armhf
            output: libRemoteInput.so.1.0.0
            release: libRemoteInput-armhf.so
            target_release_repo: Reflection
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        
    - name: Update Sources - Linux armhf
      if: matrix.config.arch == 'armhf'
      run: |
        sudo sed -Ei 's/^deb /deb \[arch=amd64\,i386\] /' /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ bionic main restricted" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ bionic-updates main restricted" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ bionic universe" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ bionic-updates universe" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ bionic multiverse" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ bionic-updates multiverse" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ bionic-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
        
        sudo dpkg --add-architecture armhf
        sudo apt-get update
        
    - name: Dependencies - Linux armhf
      if: matrix.config.arch == 'armhf'
      run: |
        sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
        sudo apt-get install libprocps-dev:armhf mesa-common-dev:armhf libglu1-mesa:armhf libglu1-mesa-dev:armhf libgl1-mesa-glx:armhf libgl1-mesa-dev:armhf libglfw3-dev:armhf cmake

    - name: CMake Generate Build Files
      if: matrix.config.arch == 'armhf'
      run: |
        cmake -S '${{ github.workspace }}' -B '${{ github.workspace }}/cmake-build-release' -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=armhf -DCMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=/usr/bin/arm-linux-gnueabihf-g++ -DCMAKE_BUILD_TYPE=Release -DOTHER_LINKER_FLAGS:STRING=${{ matrix.config.other_linker_flags }} -G "CodeBlocks - Unix Makefiles"

    - name: Build
      if: matrix.config.arch == 'armhf'
      run: |
        cmake --build '${{ github.workspace }}/cmake-build-release' --target all -- -j 4

    - name: Gather Release Notes
      id: release_notes
      if: matrix.config.arch == 'armhf' && github.event_name == 'push'
      run: |
        if [ "${{ github.event_name }}" = "push" ]; then
          commit="${{ github.event.head_commit.message }}"
          author="${{ github.event.head_commit.author.name }}"
          notes="${commit}<br /><br />- ${author}"
          notes="${notes//\\n/<br />}"
          notes="${notes//$'\n'/<br />}"
        elif [ "${{ github.event_name }}" = "pull_request" ]; then
          commit="${{ github.event.pull_request.title }}"
          body="${{ github.event.pull_request.body }}"
          author="${{ github.event.pull_request.author }}"
          notes="${commit}<br />${body}<br /><br />- ${author}"
          notes="${notes//\\n/<br />}"
          notes="${notes//$'\n'/<br />}"
        fi
        echo ::set-output name=description::"${notes}"
      shell: bash

    - name: Upload Artifacts 
      if: matrix.config.arch == 'armhf' && startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
      uses: actions/upload-artifact@v1
      with:
        name: "${{ matrix.config.output }}"
        path: '${{ github.workspace }}/cmake-build-release/${{ matrix.config.output }}'

    - name: Upload Autobuild
      if: matrix.config.arch == 'armhf' && !startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
      uses: Brandon-T/upload-release-action@master
      with:
        repo_token: ${{ secrets.CI_RELEASE_TOKEN }}
        file: '${{ github.workspace }}/cmake-build-release/${{ matrix.config.output }}'
        asset_name: '${{ matrix.config.release }}'
        tag: autobuild
        owner: '${{ github.repository_owner }}'
        repo: '${{ matrix.config.target_release_repo }}'
        release_notes: ${{ steps.release_notes.outputs.description }}
        overwrite: true

    - name: Upload Release Build
      if: matrix.config.arch == 'armhf' && startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
      uses: Brandon-T/upload-release-action@master
      with:
        repo_token: ${{ secrets.CI_RELEASE_TOKEN }}
        file: '${{ github.workspace }}/cmake-build-release/${{ matrix.config.output }}'
        asset_name: '${{ matrix.config.release }}'
        tag: '${{ github.ref }}'
        owner: '${{ github.repository_owner }}'
        repo: '${{ matrix.config.target_release_repo }}'
        release_notes: ${{ steps.release_notes.outputs.description }}
        overwrite: true