name: Windows-x86_64

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.config.name }} Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config: 
          - os: windows-latest
            name: Windows 64
            other_linker_flags: '-m64'
            arch: x86_64
            output: libRemoteInput.dll
            release: libRemoteInput-x86_64.dll
            target_release_repo: Reflection
    
    steps:
    - uses: actions/checkout@v1
      if: matrix.config.arch == 'x86_64'
      with:
        submodules: true
 
    - name: CMake Generate Build Files
      if: matrix.config.arch == 'x86_64'
      run: |
        cmake -S '${{ github.workspace }}' -B '${{ github.workspace }}/cmake-build-release' -DCMAKE_BUILD_TYPE=Release -DOTHER_LINKER_FLAGS:STRING=${{ matrix.config.other_linker_flags }} -G "CodeBlocks - Unix Makefiles"

    - name: Build
      if: matrix.config.arch == 'x86_64'
      run: |
        cmake --build '${{ github.workspace }}/cmake-build-release' --target all -- -j 4

    - name: Upload Autobuild
      if: matrix.config.arch == 'x86_64' && !startsWith(github.ref, 'refs/tags/v')
      uses: ollydev/upload-release-action@master
      with:
        repo_token: ${{ secrets.CI_RELEASE_TOKEN }}
        file: '${{ github.workspace }}/cmake-build-release/${{ matrix.config.output }}'
        asset_name: '${{ matrix.config.release }}'
        tag: autobuild
        owner: '${{ github.repository_owner }}'
        repo: '${{ matrix.config.target_release_repo }}'
        overwrite: true

    - name: Upload Artifacts 
      if: matrix.config.arch == 'x86_64' && startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v1
      with:
        name: "${{ matrix.config.output }}"
        path: '${{ github.workspace }}/cmake-build-release/${{ matrix.config.output }}'

    - name: Upload Release Build
      if: matrix.config.arch == 'x86_64' && startsWith(github.ref, 'refs/tags/v')
      uses: ollydev/upload-release-action@master
      with:
        repo_token: ${{ secrets.CI_RELEASE_TOKEN }}
        file: '${{ github.workspace }}/cmake-build-release/${{ matrix.config.output }}'
        asset_name: '${{ matrix.config.release }}'
        tag: '${{ github.ref }}'
        owner: '${{ github.repository_owner }}'
        repo: '${{ matrix.config.target_release_repo }}'
        overwrite: true